### ISSUE TITLE
Feb todo list

### ISSUE THREAD

**Issue by MengLeZhang** [DanOlner/ShinyMapEssentials#4]
- [x] -   Colour scale: you probably had this planned anyway, but there needs to be a colour scale shown alongside the maps.
- [x]  Include Logo for the project in the header
- [x]   How-to guidance information on the front page (and in other places as needed e.g. how to use the plot interactive buttons)
- [ ]         User finding TTWAs / locations:
- [x]    Postcode search / search for place name for loading a TTWA
- [x]    Fix glitches where centre doesn’t pick out TTWA (issue is making map match screen height so there’s no scroll bar, I think; also, add crosshair)
- [x] Data downloads:
~~- [ ]   As well as bulk data download in various appropriate formats (CSV, shapefile, geojson)…~~ We'll just include a big file
~~- [ ]   Have functionality to extract data for specific TTWAs, LSOAs as rows. Extract into CSV or geo-format~~

~~- [ ]   Possibly use ORDA as the source for the data. Nice thing: tells us how many people download it. Link to ORDA page.~~ Sorted via download link and asking data viz team

- [x] Summary plots tab: Plot social frontiers propensity against index of dissimilarity

- [ ] One possible for ID: LSOA as lowest for ID, so calculate at MSOA? ~5 zones for each, minimum?
- [x] Fix so can’t zoom out, fix on E+W zoom
- [ ]  What additional info to display in map mode?

- [ ] Once TTWA selected, left hand side to have display summary info. Not too much. E.g
- [x] Aggregate measure of social frontier propensity
~~- [ ]  Total length of SFs as proportion of LSOA border lengths~~ replace with prop of borders that are frontiers
- [x]  Give rank of England and Wales (Doncaster is where)
- [x]   IMD rank, index of dissimilarity
~~- [ ]  1 or 2 other seg measures, index of diversity~~ kinda confusing to explain 
- [ ]  Option to select different social frontier variable. Currently % UK born
- [ ]  Ethnicity / religion
- [ ]  Option to change colour of choropleth map to different variable than frontiers 
- [ ] lock switch to unlock different frontier / choropleth data
- [ ]   Select Census Year for Social Frontiers
- [ ]  (optional)   Option to change the scale: allow people to select higher geography like combined authorities or UK region

**Comment by DanOlner** [comment]
A couple of additional thoughts via Gwilym:

- [ ] Colour scale: you probably had this planned anyway, but there needs to be a colour scale shown alongside the maps.
- [ ] 3D rendering: this is almost certainly one for the future, but it would be very helpful in the "Summary and plots" tab for a selected TTWA to allow the user to see a rotatable 3D render of the variable in question.

**Comment by MengLeZhang** [comment]
RE: Colour scale. Are we tackling this via a legend in leaflet?

**Comment by DanOlner** [comment]
Bullet points updated to [issue 7](https://github.com/DanOlner/ShinyMapEssentials/issues/7).
