### ISSUE TITLE
GP feedback todo 31-1-2023

### ISSUE THREAD

**Issue by MengLeZhang** [DanOlner/ShinyMapEssentials#6]
Note: Not all are critical issues -- lots are suggestions

- [ ]       Include Logo for the project in the header
- [ ]    How-to guidance information on the front page (and in other places as needed e.g. how to use the plot interactive buttons)
- [ ]   User finding TTWAs / locations:

o   Postcode search / search for place name for loading a TTWA

- [ ]   Fix glitches where centre doesn’t pick out TTWA (issue is making map match screen height so there’s no scroll bar, I think; also, add crosshair)

    Data downloads:

- [ ]    As well as bulk data download in various appropriate formats (CSV, shapefile, geojson)…
- [ ]    Have functionality to extract data for specific TTWAs, LSOAs as rows. Extract into CSV or geo-format
- [ ]  Possibly use ORDA as the source for the data. Nice thing: tells us how many people download it. Link to ORDA page.

- [ ]  Summary plots tab: Plot social frontiers propensity against index of dissimilarity

o   One possible for ID: LSOA as lowest for ID, so calculate at MSOA? ~5 zones for each, minimum?
- [ ]          Fix so can’t zoom out, fix on E+W zoom
- [ ]    What additional info to display in map mode?

- [ ] Once TTWA selected, left hand side to have display summary info. Not too much. E.g
- [ ]   Aggregate measure of social frontier propensity
- [ ]  Total length of SFs as proportion of LSOA border lengths
- [ ] Give rank of England and Wales (Doncaster is where)
- [ ] IMD rank, index of dissimilarity
- [ ] 1 or 2 other seg measures, index of diversity
- [ ] Option to select different social frontier variable. Currently % UK born
- [ ] Ethnicity / religion
- [ ]  Option to change colour of choropleth map to different variable than frontiers – lock switch to unlock different frontier / choropleth data

- [ ] Select Census Year for Social Frontiers
-  ~~Option to change the scale: allow people to select higher geography like combined authorities or UK region~~ I would say this one is out of scope

**Comment by MengLeZhang** [comment]
oops duplicated
